---
title: "SDS390 Final Project"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(haven)
timedata <- read_sav("time1 - time 2 dataset for data in brief october-26-2020.sav")
```

```{r}
timedata %>%
  select(Time1_Age,Time1_Race, Time1_Illnesses, Time1_impact_of_events_scale_total, Time1_Educational_attainment, Time1_meds, Time1_patient_health_questionnaire_total,Time1_perceived_susceptibility_to_COVID19 ,Time1_general_health_quetionnaire_total, Time1_Employment_After_COVID, Time1_intolerance_of_uncertainty_total, Time1_intolerance_of_uncertainty_total, Time1_Gender, Time1_perceived_vulnerability_to_disease,Time1_self_isolation_yes_or_no,Time1_number_of_times_leave_home_per_day, Time1_preventive_action_taken_scale_avoid_travel_people,Time1_Marital_status, Time1_five_factor_mindfulness_questionnaire_total, Time1_Religious_Affiliation, Time1_preventive_action_taken_scale_avoid_travel_people, Time1_preventive_action_taken_scale_PPEuse, Time1_quality_of_life_Total) %>%
  as.data.frame() %>%
  cor(use="complete.obs")
```

```{r}
timedata %>%
  select(Time2_Annual_income,Time2_Illnesses,Time2_Meds, Time2_impact_of_events_scale_total, Time2_employment_status, Time2_patient_health_questionnaire_total, Time2_intolerance_of_uncertainty_total ,Time2_perceived_susceptibility_to_covid19 ,Time2_self_isolation_yes_or_no, Time2_five_factor_mindfulness_questionnaire_total, Time2_general_health_questionnaire_total, Time2_perceived_vulnerability_to_disease_total,Time2_preventive_action_taken_scale_PPEuse, Time2_quality_of_life_total) %>%
  as.data.frame() %>%
  cor(use="complete.obs")
```

```{r}
ggplot(data = timedata, aes(x=Time1_quality_of_life_Total)) + geom_histogram()
summary(timedata$Time1_quality_of_life_Total)
summary(timedata$Time2_quality_of_life_total)
ggplot(data = timedata, aes(x=Time1_preventive_action_taken_scale_PPEuse)) + geom_histogram()
ggplot(data = timedata, aes(x=Time1_intolerance_of_uncertainty_total)) + geom_histogram()
ggplot(data = timedata, aes(x=Time1_general_health_quetionnaire_total)) + geom_histogram()


```

```{r}
library(haven)
time1 <- read_sav("Time 1 dataset for data in brief october-26-2020.sav")
```

```{r message=FALSE, results="hide"}
library(rstan)
library(rstanarm)
set.seed(84735)
mod_a <- stan_glm(Quality_of_Life_Total ~ Age + Gender + Intolerance_of_Uncertainty_Total + Patient_Health_Questionnaire_Total + General_Health_Questionnaire_Negative_Total + Perceived_Vulnerability_to_Disease_Total + Impact_of_Events_Scale_Total,
                             data = time1,
                             family = gaussian,
                             chains = 4,
                             iter = 5000*2)

library(bayesplot)
mcmc_trace(mod_a, size = 0.1)

model_summary <- summary(mod_a)
head(as.data.frame(model_summary), -2)

```

```{r}
pois_mod2 <- stan_glm(Time1_quality_of_life_Total ~ Time1_Illnesses + Time1_general_health_quetionnaire_total + Time1_five_factor_mindfulness_questionnaire_total + Time1_Illnesses*Time1_general_health_quetionnaire_total + Time1_general_health_quetionnaire_total*Time1_five_factor_mindfulness_questionnaire_total + Time1_five_factor_mindfulness_questionnaire_total*Time1_Illnesses, 
                             data = covid,
                             family = poisson(),
                             chains = 4,
                             iter = 5000*2)
```


```{r}
##don't understand why the direction of intolerance of uncertainty changes 
##impact of events scale have vif 2.96 
mod1 <- lm(Quality_of_Life_Total ~ Age + Gender + Education + Intolerance_of_Uncertainty_Total + Patient_Health_Questionnaire_Total + General_Health_Questionnaire_Negative_Total + Perceived_Vulnerability_to_Disease_Total + Impact_of_Events_Scale_Total, data=time1)
summary(mod1)

mod1 <- lm(Quality_of_Life_Total ~ Age + Gender + Intolerance_of_Uncertainty_Total, data=time1)
summary(mod1)

library(car)
vif(mod1)

mod1 <- lm(Quality_of_Life_Total ~ Age + as.factor(Gender) + Education + Race+ Intolerance_of_Uncertainty_Total + Patient_Health_Questionnaire_Total + General_Health_Questionnaire_Negative_Total + Perceived_Vulnerability_to_Disease_Total, data=time1)
summary(mod1)


```

```{r}
set.seed(84735)
pp_check(mod_a, nreps = 50)

set.seed(84735)
mod_b <- stan_glm(Quality_of_Life_Total ~ Age + as.factor(Gender) + Education +  Intolerance_of_Uncertainty_Total + Patient_Health_Questionnaire_Total + General_Health_Questionnaire_Negative_Total + Perceived_Vulnerability_to_Disease_Total,
                             data = time1,
                             family = gaussian,
                             chains = 4,
                             iter = 5000*2)

set.seed(84735)
pp_check(mod_b, nreps = 50)

model_summary <- summary(mod_b)
head(as.data.frame(model_summary), -2)
vif(mod_b)
```

```{r}
set.seed(84735)
mod_c <- stan_glm(Preventive_Action_Taken_Scale_PPEuse_Total ~ Age + Gender + Intolerance_of_Uncertainty_Total + Patient_Health_Questionnaire_Total + General_Health_Questionnaire_Negative_Total + Perceived_Vulnerability_to_Disease_Total + Impact_of_Events_Scale_Total,
                             data = time1,
                             family = gaussian,
                             chains = 4,
                             iter = 5000*2)
```
```{r}
set.seed(84735)
pp_check(mod_c, nreps = 50)

mod3 <- lm(Preventive_Action_Taken_Scale_PPEuse_Total ~ Age + as.factor(Gender) + Education +  Intolerance_of_Uncertainty_Total + Patient_Health_Questionnaire_Total + General_Health_Questionnaire_Negative_Total + Perceived_Vulnerability_to_Disease_Total, data=time1)
summary(mod3)
```








